#!/usr/bin/env Rscript
#
# Run an estimation procedure (not necessarily MCMC) on the MrP data.
# Note that this is intended to run MAP and lmer only on the original
# data, since the analysis_type variable is currently used to
# record both the data source and estimation method.
#
# Example invocations:
# ./run_mcmc.R --base_dir=$(pwd) --original --map
# ./run_mcmc.R --base_dir=$(pwd) --original --lmer
# ./run_mcmc.R --base_dir=$(pwd) --original --save_filename=/tmp/test.Rdata

library(tidyverse)
library(brms)
library(rstan)
library(lme4)
library(optparse)

option_list <- list(
  make_option(c("--base_dir"),
              default="./",
              help="The base directory"),
  make_option(c("--data_filename"),
              default="datasets/cces18_subset.Rdata",
              help="The name of the data file (generated by generate_dataset.R)."),
  make_option(c("--seed"),
              help="The random seed to use.", 
              default=134432,
              type="integer"),
  make_option(c("--save_filename"),
              help="Optional filename and path relative to base_dir for the output"),
  make_option(c("--force"),
              action="store_true",
              default=FALSE,
              help="If set, overwrite existing results"),
  make_option(c("--subsample"),
              action="store_true",
              default=FALSE,
              help="If set, sample from the original data instead of bootstrapping."),
  make_option(c("--original"),
              action="store_true",
              default=FALSE,
              help="If set, simply run the sampler on the original dataset."),
  make_option(c("--lmer"),
              action="store_true",
              default=FALSE,
              help="If set, use lme4 instead of MCMC."),
  make_option(c("--map"),
              action="store_true",
              default=FALSE,
              help="If set, compute the MAP instead of MCMC"),
  make_option(c("--num_cores"),
              default=4,
              help="Number of cores for parallel processing"),
  make_option(c("--num_samples"),
              default=5000,
              help="Number of MCMC samples"),
  make_option(c("--num_warmup_samples"),
              default=500,
              help="Number of MCMC warmup samples"),
  make_option(c("--num_mcmc_chains"),
              default=4,
              help="Number of MCMC chains")
)


# get command line options, if help option encountered print help and exit,
# otherwise if options not found on command line then set defaults,
opt <- parse_args(OptionParser(option_list=option_list))
print("===================")
print("Options:")
print(opt)
print("===================")

set.seed(opt$seed)
setwd(opt$base_dir)

if (!file.exists(opt$data_filename)) {
  stop(sprintf("The data file %s does not exist.", opt$data_filename))
}
load(opt$data_filename)

# Determine analysis type

if (opt$original) {
    print("Running on original dataset.")
    survey_sample_df <- survey_df
    analysis_type <- "original"
} else {
  if (!opt$subsample) {
    print("Bootstrapping.")
    survey_sample_df <- sample_n(survey_df, size=nrow(survey_df), replace=TRUE)
    analysis_type <- "bootstrap"
  } else {
    print("Sampling")
    sample_size <- nrow(survey_df)
    survey_sample_df <- cces_all_df %>% sample_n(sample_size)
    analysis_type <- "subsample"
  }
}

if (opt$lmer & opt$map) {
  stop("You must not specify both --lmer and --map.")
}

if (opt$lmer) {
  print("Fitting using lmer")
  analysis_type <- paste0(analysis_type, "lmer")
} else if (opt$map) {
  print("Fitting using MAP")
  analysis_type <- paste0(analysis_type, "map")
} else {
  print("Fitting using stan")
}

# Set output file

if (is.null(opt$save_filename)) {
  save_filename <- file.path(
    opt$base_dir, 
    sprintf("bootstrap_data/mrp_%s_seed%d_samples%d.Rdata", 
            analysis_type, opt$seed, opt$num_samples))
} else {
  save_filename <- opt$save_filename
}
print(sprintf("Saving to %s", save_filename))

if (!dir.exists(dirname(save_filename))) {
  success <- dir.create(dirname(save_filename), recursive=TRUE)
  if (!success) {
    stop(sprintf("Failed to create save directory %s", dirname(save_filename)))
  }
}

if (file.exists(save_filename)) {
  sprintf("File %s exists.", save_filename)
  if (!opt$force) {
    print("Force is false; terminating.")
    if (!interactive()) {
      quit(save="no")
    }
  }
}


# Run analysis

print("Running sampler.")

regressor_string <- paste0(
  " ~ (1 | state) + (1 | eth) + (1 | educ) + male + ",
  "(1 | male:eth) + (1 | educ:age) + (1 | educ:eth) + ",
  "repvote + region")
model_string <- paste0("abortion ", regressor_string)

cat_regressors <- c("state", "eth", "educ", "male", "age", "region")
regressors <- c(cat_regressors, "repvote")
stopifnot(all(regressors %in% names(survey_df)))
stopifnot(all(regressors %in% names(pop_agg_df)))

logit_prior <- c(prior(normal(0, 2), class = b), 
                 prior(normal(0, 10.5), class = b, coef = repvote), 
                 prior(exponential(0.5), class = sd))

if (opt$lmer) {

  # Perhaps I should not call this stan_time or logit_post; but what's done is done.
  stan_time <- Sys.time()
  logit_post <- glmer(formula(model_string), 
                    family=binomial(link="logit"),
                    data=survey_sample_df)
  stan_time <- Sys.time() - stan_time
  print("Lmer fit done!")
  print(stan_time)

} else if (opt$map) {

  print("Compiling Stan model")
  code <- make_stancode(
    formula(model_string), 
    family = bernoulli(link="logit"),
    data = survey_sample_df,
    prior = logit_prior)
  data <- make_standata(
    formula(model_string), 
    family = bernoulli(link="logit"),
    data = survey_sample_df,
    prior = logit_prior)
  mod <- stan_model(model_code=code)

  # Note: this is a lousy optimum due to Stan nonsense.  You need to compute
  # your own MAP estimator using analyze_map.R.
  
  print("Starting MAP estimation")
  stan_time <- Sys.time()
  logit_post <- optimizing(mod, data=data, hessian=TRUE, draws=opt$num_samples, constrained=TRUE)
  stan_time <- Sys.time() - stan_time
  print("MAP fit done!")

  # Save the code and data, too
  logit_post$data <- data
  logit_post$code <- code
  
} else {
  stan_time <- Sys.time()
  logit_post <- brm(formula(model_string), 
                    family = bernoulli(link="logit"),
                    data = survey_sample_df,
                    prior = logit_prior,
                    control = list(adapt_delta = 0.99),
                    chains=opt$num_mcmc_chains, 
                    cores=opt$num_cores,
                    warmup=opt$num_warmup_samples, 
                    iter=opt$num_samples)
  stan_time <- Sys.time() - stan_time
  print("Sampling done!")
  print(stan_time)
}

sys_info <- Sys.info()
sys_time <- Sys.time()
save(logit_post, survey_sample_df, opt, sys_info, sys_time, stan_time,
     file=save_filename)


